export const LOAD_ENTREPRENEURS_REQUESTED = 'LOAD_ENTREPRENEURS_REQUESTED';
export const LOAD_ENTREPRENEURS_SUCCESS = 'LOAD_ENTREPRENEURS_SUCCESS';
export const LOAD_ENTREPRENEURS_FAILED = 'LOAD_ENTREPRENEURS_FAILED';

export const DELETE_ENTREPRENEUR_REQUESTED = 'DELETE_ENTREPRENEUR_REQUESTED';
export const DELETE_ENTREPRENEUR_SUCCESS = 'DELETE_ENTREPRENEUR_SUCCESS';
export const DELETE_ENTREPRENEUR_FAILED = 'DELETE_ENTREPRENEUR_FAILED';
export const CANCELED_DELETE_ENTREPRENEUR = 'CANCELED_DELETE_ENTREPRENEUR';

export const LOAD_DETAILS_REQUESTED = 'LOAD_DETAILS_REQUESTED';
export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';
export const LOAD_DETAILS_FAILED = 'LOAD_DETAILS_FAILED';

export const SAVE_ENTREPRENEUR_REQUESTED = 'SAVE_ENTREPRENEUR_REQUESTED';
export const SAVE_ENTREPRENEUR_SUCCESS = 'SAVE_ENTREPRENEUR_SUCCESS';
export const SAVE_ENTREPRENEUR_FAILED = 'SAVE_ENTREPRENEUR_FAILED';

export const UPDATE_ENTREPRENEUR_REQUESTED = 'UPDATE_ENTREPRENEUR_REQUESTED';
export const UPDATE_ENTREPRENEUR_SUCCESS = 'UPDATE_ENTREPRENEUR_SUCCESS';
export const UPDATE_ENTREPRENEUR_FAILED = 'UPDATE_ENTREPRENEUR_FAILED';
